name: Jekyll site CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Update to v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1

    - name: Install dependencies
      run: bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Check _site directory
      run: |
        echo "Checking _site directory contents:"
        ls -la ./_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
